# Generated by Django 4.2.4 on 2024-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.IntegerField()),
                ('entity', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('entity_no', models.IntegerField()),
                ('ownership', models.CharField(max_length=100)),
                ('entity_sector', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('transaction_no', models.CharField(max_length=50)),
                ('loan_code', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField()),
                ('deployment_date', models.DateField(blank=True, null=True)),
                ('expected_settlement_date', models.DateField(blank=True, null=True)),
                ('actual_settlement_date', models.DateField(blank=True, null=True)),
                ('settlement_amount', models.FloatField()),
                ('admin_structuring_fee', models.FloatField()),
                ('monthly_interest_charged', models.FloatField()),
                ('default_interest', models.FloatField()),
                ('pd', models.FloatField()),
                ('credit_rating', models.CharField(max_length=50)),
                ('rating_code', models.IntegerField()),
                ('model_pricing', models.FloatField()),
                ('risk_band', models.CharField(max_length=100)),
                ('cession_of_debtors', models.CharField(max_length=3)),
                ('personal_continuing_cover_surety', models.CharField(max_length=3)),
                ('cession_of_bank_accounts', models.CharField(max_length=3)),
                ('g_pay', models.CharField(max_length=3)),
                ('cession_of_payment', models.CharField(max_length=3)),
                ('cession_of_contracts', models.CharField(max_length=3)),
                ('cession_of_shares', models.CharField(max_length=3)),
                ('value_of_ceded_collateral', models.FloatField()),
                ('offtaker_name', models.CharField(max_length=100)),
                ('offtaker_type', models.CharField(max_length=100)),
                ('offtaker_sector', models.CharField(max_length=100)),
                ('jobs_created', models.IntegerField()),
                ('jobs_saved', models.IntegerField()),
                ('average_salary_per_job', models.FloatField()),
            ],
        ),
    ]
