# Generated by Django 4.2.4 on 2024-05-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='LoanDatabase',
        ),
    ]
