# Generated by Django 4.2.4 on 2024-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_loan_loandatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('portfolio_pd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.CharField(max_length=10)),
                ('return_on_loan_book', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_on_cash', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_loans_advanced', models.IntegerField()),
                ('number_of_loans_outstanding', models.IntegerField()),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accrued_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('capital_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('provision_for_expected_credit_losses', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
