# Generated by Django 4.2.4 on 2024-08-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_variablescoring_variableweighting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableScoring',
        ),
        migrations.DeleteModel(
            name='VariableWeighting',
        ),
    ]
