# Generated by Django 4.2.4 on 2024-01-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_contract_offtakerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('job_description', models.TextField()),
                ('payment_terms', models.TextField()),
            ],
        ),
    ]
