# Generated by Django 4.2.4 on 2024-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_similar_transactions', models.IntegerField()),
                ('management_experience', models.IntegerField()),
                ('sourcing_of_service_rendered', models.CharField(max_length=50)),
                ('likelihood_of_service_delivery_delay', models.CharField(max_length=50)),
                ('debt_service_cover_ratio', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('no_cash_inflows_off_taker', models.IntegerField()),
                ('avg_cash_inflow_loan_coverage', models.FloatField()),
                ('past_disputes_off_taker', models.CharField(max_length=50)),
                ('off_taker_reputational_risk', models.CharField(max_length=50)),
                ('term_to_loan_settlement_weeks', models.IntegerField()),
                ('reputational_risk', models.CharField(max_length=50)),
                ('availability_of_substitutes', models.IntegerField()),
                ('no_suppliers_to_be_used', models.IntegerField()),
                ('no_times_sme_used_suppliers', models.FloatField()),
                ('unencumbered_assets_unsecured_debt', models.FloatField()),
                ('liquid_asset_loan_coverage_ratio', models.FloatField()),
                ('pv_future_cash_flows_loan_coverage', models.FloatField()),
                ('quality_liquid_security_loan_coverage', models.FloatField()),
                ('rating', models.CharField(max_length=3)),
                ('rating_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VariableWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_number', models.CharField(max_length=50)),
                ('group_factor', models.CharField(max_length=100)),
                ('factor_variable', models.CharField(max_length=100)),
                ('purchase_order_financing', models.FloatField()),
                ('invoice_discounting', models.FloatField()),
                ('contract_financing', models.FloatField()),
            ],
        ),
    ]
